apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.region }}-{{ .Values.env }}-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-{{ .Values.region }}-{{ .Values.env }}-app
